
" Misc settings

source ~/.vim/bundles.vim

set number                    " Shows the line number on the left
set autoindent                " When you hit enter automatically be indented the correct amount
set expandtab                 " uses spaces instead of tabs (watch out for makefiles they require tabs instead of spaces)
set shiftwidth=4              " This controls the indenting when you use >> or <<
set softtabstop=4             " This doesnt really matter with expandtab on but w/e
set tabstop=4                 " use 4 spaces to tab
set showmatch                 " highlight matching parens or braces
set history=100
set hlsearch                  " when you search highlight what you just searched for
set visualbell                " Dont make an annoying ping when you do something wrong
set encoding=utf-8
set fileencoding=utf-8
color darkblue                " the torte scheme is personal preference but there are lots of good color schemes
syntax on                     " Syntax highlighting is useful

filetype plugin on
"autocmd ColorScheme * highlight ColorColumn ctermbg=235 guibg=#2c2d27
"highlight ColorColumn ctermbg=250 guibg=#2c2d27
"let &colorcolumn=join(range(81,90),",")
"match ErrorMsg '\%>91v.\+'
"

highlight OverLength ctermbg=red ctermfg=white guibg=#592929
function OverLength()
    match OverLength /\%81v.\+/
endfunction
function OverLength72()
    match OverLength /\%73v.\+/
endfunction

highlight FindColor ctermbg=red guibg=#592929
function Colorfind()
    match FindColor  /\(\%#.*\)\@<=f/
endfunction

" qq - record macro
" q  - stop recording macro
" Q  - replay macro
noremap Q @q

" powerline settings
"let g:Powerline_symbols = "fancy"

" mappings
nnoremap <silent> <F8> :TlistToggle<CR>
nnoremap <silent> <F9> :NERDTreeToggle<CR>

nmap <silent> <C-n> :tabnext<CR>
nmap <silent> <C-p> :tabprev<CR>

nnoremap <leader>. :CtrlPTag<cr>

