#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

xrdb -merge ~/.Xresources

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

DEFAULTSESSION=awesome

case "$1" in
        awesome)    exec awesome;;
        cinnamon)   exec cinnamon-session;;
        lxde)       exec startlxde;;
        *)          exec $DEFAULTSESSION;;
esac

